-- Drop and recreate markers table

DROP TABLE IF EXISTS markers CASCADE;
CREATE TABLE markers (
  id SERIAL PRIMARY KEY NOT NULL,
  creator_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
  lat DECIMAL NOT NULL,
  long DECIMAL NOT NULL,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(140) NOT NULL,
  image_url VARCHAR(255) NOT NULL
);
